apiVersion: apps/v1
kind: Deployment
metadata:
  name: financeapp-deployment
  labels:
    app: financeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: financeapp
  template:
    metadata:
      labels:
        app: financeapp
    spec:
      containers:
        - name: financeapp-container
          image: sravani629/financeapp:14
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: financeapp-service
spec:
  type: NodePort
  selector:
    app: financeapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000
